import React, { useState } from 'react';
import { X, ShieldCheck } from 'lucide-react';
import toast from 'react-hot-toast';

export default function Manage2FAModal({ isOpen, onClose }) {
  const [step, setStep] = useState(1);
  const [code, setCode] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!isOpen) return null;

  const handleVerify = () => {
    if (code.length !== 6) {
      toast.error('Please enter a 6-digit code');
      return;
    }
    
    setIsSubmitting(true);
    // Mocking a verification process
    setTimeout(() => {
      setIsSubmitting(false);
      toast.success('Two-Factor Authentication Enabled!');
      onClose();
    }, 1500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-3xl w-full max-w-md shadow-2xl overflow-hidden flex flex-col" onClick={e => e.stopPropagation()}>
        <div className="flex justify-between items-center p-6 border-b border-gray-100 shrink-0">
          <div className="flex items-center gap-2 text-gray-900">
            <ShieldCheck size={20} className="text-green-600" />
            <h2 className="text-xl font-bold font-serif">Setup 2FA</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-700 bg-gray-50 hover:bg-gray-100 rounded-full p-2 transition-colors">
            <X size={20} />
          </button>
        </div>

        <div className="p-6">
          {step === 1 ? (
            <div className="flex flex-col items-center text-center space-y-4">
              <p className="text-sm text-gray-600 font-medium">
                Scan this QR code with your authenticator app (like Google Authenticator or Authy).
              </p>
              <div className="p-4 bg-white border-2 border-gray-100 rounded-2xl shadow-sm">
                <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=otpauth://totp/VionFashion:User?secret=JBSWY3DPEHPK3PXP&issuer=VionFashion" alt="QR Code" className="w-40 h-40" />
              </div>
              <p className="text-xs text-gray-400 font-medium">Secret Key: JBSWY3DPEHPK3PXP</p>
              <button 
                onClick={() => setStep(2)}
                className="w-full bg-[#3A10E5] hover:bg-[#2A08B5] text-white font-bold py-3 rounded-xl transition-all shadow-sm mt-4"
              >
                Next
              </button>
            </div>
          ) : (
            <div className="flex flex-col space-y-4">
              <p className="text-sm text-gray-600 font-medium text-center">
                Enter the 6-digit code generated by your authenticator app.
              </p>
              <div>
                <input 
                  type="text" 
                  maxLength={6}
                  value={code} 
                  onChange={e => setCode(e.target.value.replace(/\D/g, ''))} 
                  className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-center text-2xl tracking-widest font-bold focus:outline-none focus:border-[#3A10E5] focus:bg-white transition-colors" 
                  placeholder="000000"
                />
              </div>
              <button 
                onClick={handleVerify}
                disabled={isSubmitting || code.length !== 6} 
                className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 rounded-xl transition-all shadow-sm mt-4 flex justify-center items-center h-12 disabled:opacity-50"
              >
                {isSubmitting ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div> : 'Verify & Enable'}
              </button>
              <button 
                onClick={() => setStep(1)}
                className="w-full bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold py-3 rounded-xl transition-all shadow-sm"
              >
                Back
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
